Add instructions for loading database file
ospfranco/react-native-quick-sqlite pull request #75
Opened 2022-08-10 07:28 UTC by ShivamJoker

2022-08-10 07:53 UTC, ShivamJoker commented
@ospfranco It would have been better to keep the directory similar in both the OS.

2022-08-10 08:28 UTC, ospfranco requested changes

2022-08-10 08:28 UTC, ospfranco commented on README.md
> +**Note: In iOS you can't navigate out, you will have to copy the DB file in the DocumentDirectory**
You can navigate out, but only one level, because the apps are sandboxed and do not have file system wide access, better to clarify this properly

2022-08-10 08:28 UTC, ospfranco commented on README.md
> +By default in iOS the library looks intro [`NSDocumentDirectory`](https://github.com/ospfranco/react-native-quick-sqlite/blob/733e876d98896f5efc80f989ae38120f16533a66/ios/QuickSQLite.mm#L34-L35) and
the `files` directory is part off the app bundle AFAIK, better to clarify this is not a system-wide files directory

2022-08-10 08:28 UTC, ospfranco commented on README.md
> +QuickSQLite.open('prpop.db', '../databases`)
use a proper database name please

2022-08-10 08:28 UTC, ospfranco commented on README.md
> +By default in iOS the library looks intro [`NSDocumentDirectory`](https://github.com/ospfranco/react-native-quick-sqlite/blob/733e876d98896f5efc80f989ae38120f16533a66/ios/QuickSQLite.mm#L34-L35) and
Looks is not the correct expresion, the passed database name is appended and generates a final URL: `${documentsDir}/${databaseName}`

2022-08-10 08:28 UTC, ospfranco commented on README.md
> +You can either copy your database file into these location using [react-native-file-access](https://github.com/alpha0010/react-native-file-access) or use `../` to change the default directory.
"into the corresponding locations* or you can navigate using the file system using unix dot notation, e.g. `../` to change the current directory"

2022-08-11 05:19 UTC, ospfranco commented
> @ospfranco It would have been better to keep the directory similar in both the OS.

They are the same directory, the place were files are supposed to be dropped. It was also the least of my concerns in what was weeks of work researching and developing this library.

If it bothers you so much you are more than welcome to fork or even create your own version of the library, by now I won't change it since people are already using it in production.

I'll take care of the README.

2022-08-11 05:19 UTC, closed without merging